### ISSUE TITLE
Scope Projects to be Voted On

### ISSUE THREAD

**Issue by s-espinosa** [s-espinosa/demonight#109]
Only if it's M3 or M4

**Comment by notmarkmiranda** [comment]
votes arent allowed on mod 2 projects period? ie. they don't show up on the voting page?

**Comment by s-espinosa** [comment]
@notmarkmiranda Believe that's the case. Current thought/recommendation is that we include a new section for projects that aren't available to rate (I had a better word for this). Unrated? Not eligible for final? Let me know what you think. Also: believe posse projects go into that.

Side note: will likely eventually want a table with the mods on it instead of passing that array. Probably should have done that earlier, but we can handle that next inning.
