### ISSUE TITLE
notes section

### ISSUE THREAD

**Issue by notmarkmiranda** [s-espinosa/demonight#129]
add a notes section to a project
jean joris put `(please put me towards the end so my father can come see me present)` in his project name

**Comment by rtravitz** [comment]
@notmarkmiranda I think I'm going to pull this card to work on and earn my keep in the dev channel. Should the notes on a project only be visible to an admin?

**Comment by notmarkmiranda** [comment]
i think they should be editable if the user comes back to edit their project. but yes, generally only visible to admins

**Comment by rtravitz** [comment]
@notmarkmiranda Where would you like the note visible for admins. On the demo night show page with the table or on the projects index page? The projects index page layout fits notes better, but it would require an if statement in the view to only display the notes to admins there. Trying to fit the note on the demo night show page within the admin namespace might result in some long table rows, on the other hand.

**Comment by notmarkmiranda** [comment]
i'd be fine with longer rows. not that many people put notes in anyway. and if they are, it's usually just a sentence or two.

**Comment by rtravitz** [comment]
@notmarkmiranda also closing the issue that the PR addressed.
