### ISSUE TITLE
Add Number of Votes Per Project

### ISSUE THREAD

**Issue by notmarkmiranda** [s-espinosa/demonight#131]
maybe not necessary, but a cool idea in case you wanted to have weighted average?

**Comment by s-espinosa** [comment]
@notmarkmiranda Does this exist on the live scoreboard? Do we think we need it on the `admin/demonight#show`? I don't see as much need for it there, but let me know.

**Comment by notmarkmiranda** [comment]
I would say we do? Live scores board doesn't exist on past demo nights?

**Comment by s-espinosa** [comment]
@notmarkmiranda I guess what I'm thinking is that this isn't a metric that people would use for past demo nights. I'm going to close, but feel free to open again if there's something I'm not considering.
