### ISSUE TITLE
Live scoreboard

### ISSUE THREAD

**Issue by notmarkmiranda** [s-espinosa/demonight#134]

**Comment by s-espinosa** [comment]
@notmarkmiranda THIS IS A TERRIBLE IDEA. I'm watching these scores come in, but I don't want the students to be able to do that! It would completely sway voting and give them incentive to vote projects down! Convince me I'm wrong.

**Comment by notmarkmiranda** [comment]
THIS IS MY #1 PRIORITY.

Possible solutions:
API Controller & Action Cable to a 1 page React or Angular App.

**Comment by s-espinosa** [comment]
Love that this basically boils down to you being to lazy to reload. Just make sure you scope it to admin.

**Comment by notmarkmiranda** [comment]
I guess we could just set an auto reload on the admin::demo_nights#show page?

**Comment by lsaville** [comment]
Nah man you need some ajax magic that checks every second and injects the
new data into the page

**Comment by s-espinosa** [comment]
@lsaville That doesn't seem expensive at all.

**Comment by notmarkmiranda** [comment]
@s-espinosa @lsaville, Sal is sassy today on Waffle.
