### ISSUE TITLE
Fix Admin / Projects Table Column Widths

### ISSUE THREAD

**Issue by notmarkmiranda** [s-espinosa/demonight#140]
Table widths are ugly right now. fix them

**Comment by s-espinosa** [comment]
@notmarkmiranda Calling this a bug feels a little aggressive.

**Comment by notmarkmiranda** [comment]
@s-espinosa what else would you call it? it's something that's already built that needs to be fixed? an enhancement?

**Comment by s-espinosa** [comment]
@notmarkmiranda Is it broken? It still works, right? I don't actually care about this. I don't know why I'm still typing.

**Comment by notmarkmiranda** [comment]
@s-espinosa it's broken.

**Comment by s-espinosa** [comment]
@notmarkmiranda You're broken.

**Comment by notmarkmiranda** [comment]
@s-espinosa touché. also, good talk.
