### ISSUE TITLE
Leave voting open past the end of demonight

### ISSUE THREAD

**Issue by lsaville** [s-espinosa/demonight#152]
Announce the end of voting with a half hour window after the end of presentations. For users that choose to pay full attention to the presentations and vote after presentation blocks... Via complaint from user. I also am unaware of how the time to vote ends, manually or on a timer.

**Comment by s-espinosa** [comment]
@lsaville currently ends based on a button press from an admin. All we would need to do is wait to close voting.

Thoughts on another way to implement reasonably? All I can think of is a 30 minute wait after the admin hits the button (which I don't like - if I close voting it should just be closed), OR a feature where any open voting is closed at midnight of that day (admin would still want the opportunity to close voting, but wouldn't have to).

Not sure I like either of these as much as just waiting.

**Comment by s-espinosa** [comment]
@lsaville Actually, if you add a rake tasks consistent with the [Heroku documentation](https://devcenter.heroku.com/articles/scheduler), I'll add it as a scheduled task.
