### ISSUE TITLE
Archive demo nights

### ISSUE THREAD

**Issue by s-espinosa** [s-espinosa/demonight#178]
As an admin
When I click on an closed demo night with votes
and I click on archive
I am taken to the demo night show page
and I see a list of projects with the average and total scores for those projects
and the button to edit or delete a project is removed
and the buttons to accept submissions and open voting are removed
and all of the votes associated with those projects have been deleted from the database

@notmarkmiranda Does this about capture it?

**Comment by notmarkmiranda** [comment]
@s-espinosa Looks good to me. How do we want to go about implementation? Are we on a new enough version of Postgres for `jsonb`? Can we do a size comparison on a local env pre and post archiving?

**Comment by s-espinosa** [comment]
Interesting! I was thinking something like the following:

* Add an archive flag to project.
* Add a wow/challenge/representation to project
* Add conditional logic to the project model to check to see if it's been archived
    * if it has, use the information saved on the project
    * if it hasn't, use the information from the actual votes.
* Delete the historical voting information.

I know this foils your plans of saving the voting data for analysis, but...

I feel like we do one of two things:

* download a backup of the existing database.
* figure out JSONB.

I think JSONB saves us rows, which I believe is what matters on Heroku, but that might not be the full picture. I'm also not yet convinced that we'll actually do any analysis of the votes, so I'm okay losing it (or at least making it more difficult to access by downloading the backup) for an easier solution/not building something that we *think* we *might* *potentially* *maybe* use in the future.

**Comment by s-espinosa** [comment]
Closed by #179
