### ISSUE TITLE
Admin can change a demonight status

### ISSUE THREAD

**Issue by s-espinosa** [s-espinosa/demonight#20]
registration
voting
completed

**Comment by notmarkmiranda** [comment]
what do those 3 words mean? you want to be able to change those things?

**Comment by s-espinosa** [comment]
I think the idea is that these would be values for a 'status' enum that would replace the 'active' Boolean. A demo night would only be active if it wasn't closed, so if 'closed?' returns false it would be active. Might also make it worthwhile to create an 'active?' on DemoNight that simply returns '!closed?'.

**Comment by s-espinosa** [comment]
Replaced by #27
