### ISSUE TITLE
On voting index only show projects that you haven't submitted a vote on.

### ISSUE THREAD

**Issue by s-espinosa** [s-espinosa/demonight#29]

**Comment by notmarkmiranda** [comment]
Can I get a rough user story for this? I'm not sure I understand what `voting index` is?

**Comment by s-espinosa** [comment]
Yeah, this is actually the project index that allows you to vote.

As a user
When I visit `/demo_night/:id/projects`
I am presented with a list of projects

When i click on a project
and I select a score for each of the categories
and I click on submit
I am returned to `/demo_night/:id/projects`
And the project name of the project that I just voted on is no longer shown.
