### ISSUE TITLE
scope project to a user!

### ISSUE THREAD

**Issue by notmarkmiranda** [s-espinosa/demonight#39]
user can't edit their projects if they aren't scoped to them.

**Comment by s-espinosa** [comment]
@notmarkmiranda Some options:

1) A user could have two relationships to a project. One through the votes join and one directly. So on the User model, it would look something like:

```
class User < ApplicationRecord
  has_many :submitted_projects, foreign_key: "user_id", class_name: "Project"
  has_many :votes
  has_many :voted_projects, through: :votes, source: :projects
...
end
```

Will have to double check the syntax on that. Then we can use `user.submitted_projects` to find projects for the user to edit, and `user.voted_projects` to find projects that they've voted on. This will likely break everything as it currently works, but shouldn't be a huge lift to fix?

2) Use `Project.where(user_id: user.id)` if we're trying to allow a user to edit their projects, which I believe will skip the `votes` join altogether and only produce projects that the user actually created.

Thoughts?

Also, I've lost track. Don't believe we currently have any ability to edit a project. We would likely also want to return only projects related to the current DemoNight (though this could still be multiple projects if someone was submitting a personal and a group or a posse project, etc.)

**Comment by notmarkmiranda** [comment]
yep. this all looks good to me. i'll work on it tomorrow.
