### ISSUE TITLE
error, catch all route

### ISSUE THREAD

**Issue by notmarkmiranda** [s-espinosa/demonight#62]
regular user tries to navigate to admin/dashboard, need a 404

**Comment by s-espinosa** [comment]
@notmarkmiranda Isn't this what's currently happening? Is the idea that we need to re-style the 404 that's living in public?

**Comment by notmarkmiranda** [comment]
i get a rails error at the moment. i dont get a 404. unless youre okay with that. i think it'll give a `something went wrong` page in production. i was thinking more along the lines of a `get  "/errors/404",      to: "errors#show", as: "errors_404"` in the controller and a `redirect_to errors_404_path unless current_admin?` in the admin controller as a before_action

**Comment by s-espinosa** [comment]
Think I'm getting a 404 in production. The Rails error will display as long as your in dev, right? That 404 looks pretty much like a Rails error, though. Just the one saying "The page you were looking for doesn't exist." Let me know if there's something I'm missing.
